# Generated by Django 5.1.7 on 2025-03-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(default='Unknown')),
                ('species', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField()),
                ('age', models.PositiveIntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(default='Unknown')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('vaccinated', models.BooleanField(default=False)),
                ('breed', models.CharField()),
                ('description', models.TextField(default='Unknown')),
            ],
        ),
        migrations.CreateModel(
            name='Exotic_Animal',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region_of_origin', models.CharField()),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('type_of_animal', models.CharField()),
                ('vaccinated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('number_of_pets', models.IntegerField(default=1)),
            ],
        ),
    ]
